[package]
name = "astroport-tests"
version = "1.0.0"
authors = ["Astroport"]
edition = "2021"
repository = "https://github.com/astroport-fi/astroport-governance"
homepage = "https://astroport.fi"

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw2 = "0.15"
cw20 = "0.15"
cosmwasm-std = "1.1"

cosmwasm-schema = "1.1"
cw-multi-test = "0.15"
paloma = { git = "ssh://git@github.com/palomachain/palomaswap-amm.git"}

astroport-escrow-fee-distributor = { path = "../../contracts/escrow_fee_distributor" }
astroport-governance = { path = "../astroport-governance" }
voting-escrow = { path = "../../contracts/voting_escrow" }
generator-controller = { path = "../../contracts/generator_controller" }
paloma-generator = { git = "ssh://git@github.com/palomachain/palomaswap-amm.git"}
paloma-pair = { git = "ssh://git@github.com/palomachain/palomaswap-amm.git"}
paloma-factory = { git = "ssh://git@github.com/palomachain/palomaswap-amm.git"}
paloma-token = { git = "ssh://git@github.com/palomachain/palomaswap-amm.git"}
paloma-staking = { git = "ssh://git@github.com/palomachain/palomaswap-amm.git"}
paloma-whitelist = { git = "ssh://git@github.com/palomachain/palomaswap-amm.git"}
anyhow = "1"
